version: "3.8"

services:
  app:
    build: .
    container_name: redis-app
    restart: always
    environment:
      - EMAIL=zastawa777@gmail.com
      - DESEC_TOKEN=8GM6miDQkSC5TpsuFv8yXjVWd221
      - RENEW_INTERVAL=21600
      - RENEW_BEFORE_DAYS=30
      - DOMAIN_DIR=/server_data
    volumes:
      - ./server_data:/server_data
      - ./lego:/data/lego
      - ./ssl:/opt/ssl
      - ./configs:/configs    # если приложению тоже нужны configs
    ports:
      - "6379:6379"
      - "8080:8080"
      - "9100:9100"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      # твой конфиг Prometheus на хосте → в контейнер
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # данные Prometheus
      - ./prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - "9090:9090"
    environment:
      TZ: "Europe/Moscow"
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
