version: "3.9"

services:
  redis:
    build: .
    container_name: redis-from-source
    restart: always        # автозапуск и перезапуск, если упал
    ports:
      - "6379:6379"
    # Если нужен внешний volume для данных:
    # volumes:
    #   - ./data:/data
