global:
  scrape_interval: 15s

scrape_configs:
  - job_name      : "prometheus"
    static_configs:
      - targets:
        - 155.212.221.52:9090
  - job_name      : "node_exporter"
    static_configs:
      - targets:
        - 45.84.224.86:9100
